# Generated by Django 5.2.6 on 2025-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kasbiy_Standart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soha', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kasbiy_Standart_Atamalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atama', models.CharField(max_length=50)),
                ('izoh', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Kasbiy_Standart_Huquqiy_Hujjat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hujjat', models.TextField()),
            ],
        ),
    ]
